### ISSUE TITLE
renaming `zarr_metadata` to `v04.zarr_metadata` breaks downstream libraries

### ISSUE THREAD

**Issue by TimMonko** [thewtex/ngff-zarr#122]
See [bioio Issue#14](https://github.com/bioio-devs/bioio/issues/78) for an example on how this breaks downstream libraries. 

Is the plan to have the two (v0.5 and 0.4) `zarr_metadata` modules going forward? Should developers adjust to the new module name? Could an alias be used?

**Comment by thewtex** [comment]
Hi @TimMonko , thanks for the report. 🙏 

Yes, we will have more, e.g. v0.6, `zarr_metadata` modules in the future.

We could have an alias module, `ngff_zarr.zarr_metadata`, that imports everything from the module that is the default in `to_ngff_zarr` (currently v0.4). Would that address the bioio use case?

**Comment by TimMonko** [comment]
To me, that sounds reasonable. Hopefully @toloudis can give feedback, since they are the developer of the writer that uses `ngff-zarr`. I'm just a user of `bioio` myself lol

**Comment by thewtex** [comment]
@TimMonko @toloudis thanks -- implemented in #123 and released in ngff-zarr 0.10.1.

**Comment by TimMonko** [comment]
Thank you for the speedy update!

**Comment by toloudis** [comment]
Thanks for this!  We are a little behind in working with ome-zarr 0.5 (ramping up some work on supporting that now-ish, starting with reading/viewing) but at the same time I'd like to acknowledge that `ngff-zarr` is a really nice library.  Ultimately what bioio needs is a nice metadata DataClass-like model, or as close to that as we can get. (Not to discount the tricky work of converting huge dask delayed arrays to zarr)  ome-types is another library that does something similar with metadata model.
